# -*- coding: utf-8 -*-
"""Hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FnCFOo32QNe1mxRv9EzZOhjuErV9AfNY
"""

print("Hello world!")